name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Full Commit Hash
        type: string
        required: true
      default-bump:
        description: Default Version Bump (if none found in commit messages)
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch
        required: false

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}

      - name: Create Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.default-bump }}
          create_annotated_tag: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.new_tag }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}

  build-push:
    name: Build and Push
    needs: [create-release]
    uses: ./.github/workflows/build_push.yaml
    with:
      commit: ${{ github.sha }}
      tags: latest,${{ needs.create-release.outputs.tag }}
    secrets: inherit
